[package]
name = "remotrix"
version = "0.1.4"
edition = "2021"
description = "Rust-native download manager inspired by Motrix"
license = "MIT"

[[bin]]
name = "remotrix"
path = "src/main.rs"

[dependencies]
aria2-ws = "0.5"
iced = { version = "0.14", features = ["tokio", "advanced", "canvas", "svg", "markdown"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
directories = "6"
rfd = "0.17"
image = { version = "0.25", default-features = false, features = ["png"] }
dark-light = "2.0"
fluent-templates = "0.15.1"
futures = "0.3"
base64 = "0.23"
hex = "0.4"
num-traits = "0.2"
reqwest = { version = "0.13", default-features = false, features = ["rustls", "json", "socks"] }
sha2 = "0.11"
rusqlite = { version = "0.40", features = ["bundled", "fallible_uint"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
open = "5"
libc = "0.2"
fontdb = "0.24"
sys-locale = "0.3"
iced_aw = { version = "0.14", default-features = false }
iced_anim = "=0.3.1"
app-single-instance = "0.1"
notify-rust = { version = "4.17", features = ["tokio"] }
ldtray = "=0.1.2"
salvo = { version = "0.95", default-features = false, features = [
    "cors",
    "server",
    "server-handle",
    "http1",
] }

[build-dependencies]
iced_lucide = "0.1"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62", features = [
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Registry",
    "Win32_System_Variant",
    "Win32_Security",
    "Win32_UI_Shell",
    "Win32_UI_Shell_PropertiesSystem",
] }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
debug = false
overflow-checks = true

[profile.dist]
inherits = "release"
lto = "thin"
codegen-units = 16
