module = "ui::icon"

[icons]
list = "list"
folder_clock = "folder-clock"
plus = "plus"
info = "info"
settings = "settings"
refresh = "refresh-cw"
play = "play"
pause = "pause"
trash = "trash-2"
folder_open = "folder-open"
copy = "copy"
circle_alert = "circle-alert"
external_link = "external-link"
circle_help = "circle-question-mark"
connections = "plug"
layers = "layers"
download_arrow = "arrow-down-to-line"
circle_check = "circle-check"
sliders = "sliders-horizontal"
triangle_alert = "triangle-alert"
circle_x = "circle-x"
arrow_up = "arrow-up-from-line"
download = "download"
magnet = "magnet"
share = "share-2"
globe = "globe"
wrench = "wrench"
minus = "minus"
square = "square"
x = "x"
chevron_right = "chevron-right"
chevron_down = "chevron-down"
file = "file"
folder = "folder"
collapse = "chevrons-down-up"
expand = "chevrons-up-down"
